#ifndef DTCC_MESHER_PUBLIC_VERSION_H
#define DTCC_MESHER_PUBLIC_VERSION_H

#define DTCC_MESHER_VERSION_MAJOR 0
#define DTCC_MESHER_VERSION_MINOR 1
#define DTCC_MESHER_VERSION_PATCH 0

#define DTCC_MESHER_VERSION_STRING "0.1.0"

#endif
